names = ["Ali", "Yağmur", "Hakan", "Deniz"]
years = [1998, 2000, 1998, 1987]
# names.append("Cenk")
# print(names)
# names.insert(0,"Sena")
# print(names)
# names.remove("Deniz")
# print(names)
# print(names.index("Deniz"))
# print("Ali" in names)
# print(list(reversed(names)))
# names.reverse()
# print(names)
# print(sorted(names))
# names.sort()
# print(names)
# print(sorted(years))
# years.sort()
# print(years)
# str = "Chevrolet, Dacia"
# print(str.split(","))
# print(max(years))
# print(years.count(1998))
# years.clear()
# print(years)
# marka1 = input("Bir marka ismi giriniz")
# marka2 = input("Bir marka ismi giriniz")
# marka3 = input("Bir marka ismi giriniz")
# markalar = [marka1, marka2, marka3]
# print(markalar)
# markalar.append(str)
# print(markalar)